### signup user
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "full_name": "test",
    "email": "test@gmail.com",
    "password": "12345678"
}


### signin user (valid)
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "12345678"
}

@token = {{signin.response.body.token}}

### signin user (invalid)
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "12345678"
}

### get chat list
GET http://localhost:6688/api/chat
Authorization: Bearer {{token}}
